### ISSUE TITLE
Colliding with grandstand in Radiator makes them rotate crazy

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#70] opened 2019-11-08 22:43 UTC
If any car collides with a grandstand in the Radiator track, they will start to rotate crazy fast and eventually disappear.
If you collide with a grandstand in a different track, this does not happen. Strange.

Version: 61ada1e

**Comment by juzzlin** [comment] 2019-12-27 16:43
I couldn't reproduce this with the current master so closing. I tried to collide with every grandstand object in Radiator, but didn't see this happening.

**Closed by juzzlin** 2019-12-27 16:43 UTC
Labels: bug

**Comment by Wuzzy2** [comment] 2020-05-08 23:19
I had this bug again!

Start the game and select PLAY. But now comes the trick! Hold down the enter key pressed until you enter the race. You should start on the Ring track. I manage to make the grandstand spin again. Also the green bushes.

7df851b2194e7ee9cefdad6f496162c82b87aabb
